/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author giro7
 */
public class NewJFrame extends javax.swing.JFrame {


    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNota1 = new javax.swing.JTextField();
        txtNota2 = new javax.swing.JTextField();
        txtNota3 = new javax.swing.JTextField();
        txtNota4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtR = new javax.swing.JTextArea();
        Mostrar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        txtAlumno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 600));
        setPreferredSize(new java.awt.Dimension(750, 600));
        getContentPane().setLayout(null);

        txtNota1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nota 1"));
        getContentPane().add(txtNota1);
        txtNota1.setBounds(117, 135, 110, 52);

        txtNota2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nota 2"));
        getContentPane().add(txtNota2);
        txtNota2.setBounds(233, 135, 110, 52);

        txtNota3.setBorder(javax.swing.BorderFactory.createTitledBorder("Nota 3"));
        getContentPane().add(txtNota3);
        txtNota3.setBounds(117, 193, 110, 52);

        txtNota4.setBorder(javax.swing.BorderFactory.createTitledBorder(" Nota 4"));
        getContentPane().add(txtNota4);
        txtNota4.setBounds(233, 193, 110, 52);

        txtR.setColumns(20);
        txtR.setRows(5);
        jScrollPane1.setViewportView(txtR);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(233, 263, 363, 270);

        Mostrar.setText("Mostrar");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });
        getContentPane().add(Mostrar);
        Mostrar.setBounds(380, 135, 101, 52);

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar);
        Limpiar.setBounds(493, 135, 103, 52);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir);
        Salir.setBounds(608, 135, 103, 52);

        txtAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre Alumno"));
        txtAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlumno);
        txtAlumno.setBounds(233, 34, 321, 55);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
if (valida().equals("")){
    
    String alumno=getAlumno();
    double nota1=getNota1();
    double nota2=getNota2();
    double nota3=getNota3();
    double nota4=getNota4();
    double promedio=calculaPromedio(nota1, nota2, nota3, nota4);
    double altaNota=determinaAltaNota(nota1, nota2, nota3, nota4);
    double bajaNota=determinaBajaNota(nota1, nota2, nota3, nota4);
    String criterio=determinaCriterio(promedio);
    imprimir(promedio, altaNota, bajaNota, criterio);
    guardar();

}else {
    JOptionPane.showMessageDialog(null,
    "Verificar los datos en el campo "+valida());
}                 
    }//GEN-LAST:event_MostrarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
 limpiar();
    }//GEN-LAST:event_LimpiarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
int r=JOptionPane.showOptionDialog(this,
 "Estas seguro de salir...?",
 "Validacion…!!!",
 JOptionPane.YES_NO_OPTION,
 JOptionPane.QUESTION_MESSAGE,
 null,null,null);
if (r==0) System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void txtAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlumnoActionPerformed
String getAlumno(){
return txtAlumno.getText();
}
double getNota1(){
return Double.parseDouble(txtNota1.getText());
}

double getNota2(){
return Double.parseDouble(txtNota2.getText());
}

double getNota3(){
return Double.parseDouble(txtNota3.getText());
}

double getNota4(){
 return Double.parseDouble(txtNota4.getText());
}
String valida(){
 if (getAlumno().equals("")){
 txtAlumno.setText("");
 txtAlumno.requestFocus();
 return "Nombre del Alumno";
 } else if (txtNota1.getText().equals("") || getNota1()<0 ||
 getNota1()>20){
 txtNota1.setText("");
 txtNota1.requestFocus();
 return "Nota 1";
 } else if (txtNota2.getText().equals("") || getNota2()<0 ||
 getNota2()>20){
 txtNota2.setText("");
 txtNota2.requestFocus();
 return "Nota 2";
 } else if (txtNota3.getText().equals("") || getNota3()<0 ||
 getNota3()>20){
 txtNota3.setText("");
 txtNota3.requestFocus();
 return "Nota 3";
 } else if (txtNota4.getText().equals("") || getNota4()<0 ||
 getNota4()>20){
 txtNota4.setText("");
 txtNota4.requestFocus();
 return "Nota 4";
 } else
 return "";
}

double calculaPromedio(double n1,double n2,double n3,double n4){
 return (n1+n2+n3+n4)/4.0;
}

double determinaAltaNota(double n1,double n2,double n3,double n4){
 double mayor=0;
 if (n1>n2) mayor=n1; else mayor=n2;
 if (n3>mayor) mayor=n3;
 if (n4>mayor) mayor=n4;
 return mayor;
}

double determinaBajaNota(double n1,double n2,double n3,double n4){
 double menor=0;
 if (n1<n2) menor=n1; else menor=n2;
 if (n3<menor) menor=n3;
 if (n4<menor) menor=n4;
 return menor;
}

String determinaCriterio(double promedio){
 if (promedio>10)
 return "Aprobo por "+String.valueOf(promedio-10)+" puntos";
 else
 return "Desaprobo por "+String.valueOf(11-promedio)+" puntos";
}
void guardar(){
    try {
        Connection con = Conexion.getConexion();
        
        String sql = "INSERT INTO alumnos(nombre, nota1, nota2, nota3, nota4, promedio) VALUES (?,?,?,?,?,?)";
        
        PreparedStatement ps = con.prepareStatement(sql);
        
        ps.setString(1, getAlumno());
        ps.setDouble(2, getNota1());
        ps.setDouble(3, getNota2());
        ps.setDouble(4, getNota3());
        ps.setDouble(5, getNota4());
        
        double promedio = calculaPromedio(getNota1(), getNota2(), getNota3(), getNota4());
     
        
        ps.setDouble(6, promedio);
        
        ps.executeUpdate();
        
        javax.swing.JOptionPane.showMessageDialog(null, "Datos guardados correctamente");
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e);
    }
}
void imprimir( double promedio,double altaNota,
 double bajaNota, String criterio){
 txtR.setText("");
 txtR.append("ALUMNO: "+getAlumno());
 txtR.append("\nNOTA 1: "+getNota1());
 txtR.append("\nNOTA 2: "+getNota2());
 txtR.append("\nNOTA 3: "+getNota3());
 txtR.append("\nNOTA 4: "+getNota4());
 txtR.append("\n--------------------------------");
 txtR.append("\nPROMEDIO: "+promedio);
 txtR.append("\nALTA NOTA: "+altaNota);
 txtR.append("\nBAJA NOTA: "+bajaNota);
 txtR.append("\nCRITERIO: "+criterio);
}

void limpiar(){
 txtAlumno.setText("");
 txtNota1.setText("");
 txtNota2.setText("");
 txtNota3.setText("");
 txtNota4.setText("");
 txtR.setText("");
 txtAlumno.requestFocus();
}

 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Mostrar;
    private javax.swing.JButton Salir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAlumno;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtNota3;
    private javax.swing.JTextField txtNota4;
    private javax.swing.JTextArea txtR;
    // End of variables declaration//GEN-END:variables
}
