/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author giro7
 */
public class Publicidad extends javax.swing.JFrame {

    /**
     * Creates new form Publicidad
     */
    public Publicidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCantidad = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtR = new javax.swing.JTextArea();
        btnSalir = new javax.swing.JButton();
        cboMedios = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 700));
        setPreferredSize(new java.awt.Dimension(750, 700));
        getContentPane().setLayout(null);

        txtCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad de contratos"));
        getContentPane().add(txtCantidad);
        txtCantidad.setBounds(396, 66, 237, 60);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(116, 187, 237, 56);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(396, 191, 237, 48);

        txtR.setColumns(20);
        txtR.setRows(5);
        jScrollPane1.setViewportView(txtR);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(116, 288, 517, 225);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(120, 530, 148, 55);

        cboMedios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comerciales de television", "Anuncios en revistas", "Anuncios en suplementos dominicales" }));
        cboMedios.setBorder(javax.swing.BorderFactory.createTitledBorder("Medios de publicidad"));
        getContentPane().add(cboMedios);
        cboMedios.setBounds(116, 66, 237, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
int medio = getMedio();
int cantidad = getCantidad();
double precio = asignaPrecio(medio);
double bruto = calculaBruto(cantidad, precio);
double descuento = calculaDescuento(bruto);
double neto = calculaNeto(bruto, descuento);
imprimir(precio, bruto, descuento, neto);
guardarDatos(cantidad, precio, bruto, descuento, neto);

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
cboMedios.setSelectedIndex(-1);
txtCantidad.setText("");
txtR.setText("");
cboMedios.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
int r=JOptionPane.showOptionDialog(this,"Estas seguro de salir?","Publicidad",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
if (r==0) System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

 public void frmPublicidad(){
    initComponents();
    llenaMedios();
   }
    void llenaMedios() {
cboMedios.addItem("Comerciales de Television");
cboMedios.addItem("Anuncios en Revistas");
cboMedios.addItem("Anuncios en suplementos dominicales");
}
int getMedio(){
return cboMedios.getSelectedIndex();
}

int getCantidad(){
return Integer.parseInt(txtCantidad.getText());
}

double asignaPrecio(int medio){ 
switch(medio){
case 0: return 30000;
case 1: return 15000;
default: return 25000;
}
}
double calculaBruto (int cantidad, double precio){ return cantidad*precio;
}
double calculaDescuento (double bruto){
if (bruto<=5)
return bruto*0.1;
else if (bruto<=10)
return bruto*0.25;
else
return bruto*0.3;
}
double calculaNeto (double bruto, double descuento){ return bruto-descuento;
}
void imprimir (double precio, double bruto,double descuento, double neto){
txtR.setText("");
txtR.append("Medio de Publicidad: "+ cboMedios.getSelectedItem());
txtR.append("\nPrecio: $ "+String.format("%.2f", precio)); 
txtR.append("\n-----·--------");
txtR.append("\nMonto Bruto: $ "+String.format("%.2f",bruto)); 
txtR.append("\nMonto de Descuento: $ "+
String.format("%.2f", descuento)); txtR.append("\nMonto Neto: $ "+String.format("%.2f", neto));
}
void guardarDatos(int cantidad, double precio, double bruto, double descuento, double neto) {

    try {
        Connection con = Conexion2.getConnection();

        String sql = "INSERT INTO publicidad (medio, cantidad, precio, bruto, descuento, neto) VALUES (?, ?, ?, ?, ?, ?)";

        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, cboMedios.getSelectedItem().toString());
        ps.setInt(2, cantidad);
        ps.setDouble(3, precio);
        ps.setDouble(4, bruto);
        ps.setDouble(5, descuento);
        ps.setDouble(6, neto);

        ps.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(null, "Datos guardados correctamente");

    } catch (Exception e) {
        System.out.println("Error al guardar: " + e.getMessage());
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Publicidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Publicidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Publicidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Publicidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Publicidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboMedios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextArea txtR;
    // End of variables declaration//GEN-END:variables
}
